### ISSUE TITLE
PHP 7.4 compatibility?

### ISSUE THREAD

**Issue by tomaszkane** [yiisoft/yii-runner-console#17]
### What steps will reproduce the problem?
Use yii-console with PHP 7.4, try to use it with yii-console-runner.

### What is the expected result?
Composer update works.

### What do you get instead?
Got composer problem with PHP require version -> 8.0.

### Additional info

Why this package require PHP 8.0? When (almost?) all other core Yii3 packages work with 7.4? yii-console works with 7.4 and 8.0.
Does this package must-have PHP 8.0 for some new feature?

| Q                | A
| ---------------- | ---
| Version          | 1.0.0
| PHP version      | 7.4
| Operating system | Linux

**Comment by rustamwin** [comment]
All yii-* packages will support PHP 8.0 and above. Other packages will raise the PHP version to 8 as needed.

It makes no sense to support version 7.4 as this version is no longer actively [maintained](https://www.php.net/supported-versions.php).

**Comment by tomaszkane** [comment]
OK, it sounds legit. But does _requirenment_ should mean "Package works with PHP version X" instead of "Package works and have support for PHP version X"?

Now I have another reason to migrate from 7.4 in my company (it a profit :)).

**Comment by rustamwin** [comment]
Yes. The requirement is mentioned in the readme.
